### ISSUE TITLE
Upgrade CssToInlineStyles library to 2.0

### ISSUE THREAD

**Issue by hkdobrev** [OpenBuildings/swiftmailer-css-inliner#12]
The 2.0.0 release of CssToInlineStyles is imminent: https://github.com/tijsverkoyen/CssToInlineStyles/pull/111

It would have some breaking changes and lot of improvements. We could bump the version of this package to 0.4.0 (well, basically we may not bump it up, but because people has used that through some facades where they access the options on the CssToInlineStyles library so it would be a good idea). So this means we can put some other breaking changes too if needed.

From what I see so far, if people want to modify something or to inject another instance of the inliner object, we would need to support injecting a [`Processor`](https://github.com/tijsverkoyen/CssToInlineStyles/blob/4e7c36c20f96fcfd62d69f46ce6e567b4b65681d/src/Css/Rule/Processor.php) instance.

**Comment by Hikariii** [comment]
+1
