### ISSUE TITLE
Support CssToInlineStyles 2.2

### ISSUE THREAD

**Issue by hkdobrev** [OpenBuildings/swiftmailer-css-inliner#25]
From https://github.com/OpenBuildings/swiftmailer-css-inliner/pull/20#issuecomment-377187925

## 0.5
✅ Now released! 🎉

* php versions supported: 5.4, 5.5, 5.6, 7.0 and 7.1
* swiftmailer: 5.x
* css-to-inline-styles:  2.1.x

This is the current state of master.

## 0.6

* php versions supported: 5.6, 7.0, 7.1, 7.2
* swiftmailer: 5.x
* css-to-inline-styles:  2.2.x

## 0.7 or 1.0.0

* php versions supported: 7.0, 7.1, 7.2
* swiftmailer: 6.x
* css-to-inline-styles:  2.2.x

---

@nclsHart Actually, why should we publish new minor releases locking specific minor releases of the `tijsverkoyen/css-to-inline-styles` package?

Shouldn't we actually allow different versions as long as there aren't any breaking changes? Or the tests are worrying you as there are quite a few changes to the output in 2.2?

**Comment by hkdobrev** [comment]
Also, I'd drop PHP 7.0 from `0.7` as its active support has ended and soon the security fixes would stop as well.

**Comment by nclsHart** [comment]
@hkdobrev You're absolutely right about `tijsverkoyen/css-to-inline-styles`, there is no need for locking on 2.2.x. We shouldn't have any problem with the latest changes in the tests. Staying on `^2.1` should be ok.

Regarding the dropping of PHP 7.0 in `0.7`, I'm more divided. Yes, this version is not in active support anymore but I think staying on the same range of supported versions than swiftmailer could be coherent too.

**Comment by hkdobrev** [comment]
> Staying on ^2.1 should be ok.

OK, I'd try that. We can then release it as `0.5.x` version :)

**Comment by hkdobrev** [comment]
Fair enough

**Comment by nclsHart** [comment]
> We can then release it as 0.5.x version :)

👍
