### ISSUE TITLE
Drop EOL PHP versions

### ISSUE THREAD

**Issue by hkdobrev** [OpenBuildings/swiftmailer-css-inliner#28]
- [x] PHP 5.4
- [ ] PHP 5.5

**Comment by hkdobrev** [comment]
Actually, CssToInlineStyles is supported on PHP 5.5+ only since 2.0. So we could drop PHP 5.4 in `0.5.x`.

**Comment by nclsHart** [comment]
> So we could drop PHP 5.4 in 0.5.x.

I could split #20 in two parts in order to do that.
